### ISSUE TITLE
I can't find the zip folder

### ISSUE THREAD

**Issue by Kirbiv** [DamagingRose/Rose-Grabber#172] opened 2023-10-25 15:15 UTC
I can't find the zip folder with the file. I can only see the file not in the zip and when I try to open it says: You can't open this file

**Comment by gumbobr0t** [comment] 2023-10-25 15:22
its a password protected archive with the password rose123...

**Comment by Kirbiv** [comment] 2023-10-25 15:29
No
I can't find the zip. Literally.

**Comment by gumbobr0t** [comment] 2023-10-25 15:31
send log files and rebuild without password protected zip thing, will just drop the exe in the dir

**Comment by Kirbiv** [comment] 2023-10-25 15:33
I didn't add the protected zip

**Comment by Kirbiv** [comment] 2023-10-25 15:35
yes

**Comment by Kirbiv** [comment] 2023-10-25 15:36
I have bin folder without the exe

**Comment by gumbobr0t** [comment] 2023-10-25 15:37
why would it be in the bin folder?? its in the normal root from the rose grabber dir

**Comment by Kirbiv** [comment] 2023-10-25 15:37
wait what,

**Comment by gumbobr0t** [comment] 2023-10-25 15:43
are you stupid? its located in the root directory of rose-stealer, its in the directory where the builder.bat is located, if it isnt, im aksing you again to send me the log files (roselog.log, rosecompile.log)

**Comment by gumbobr0t** [comment] 2023-10-25 15:45
do i look like a fricking magician or how am i supposed to see what the issue is? i need the log files!

**Comment by gumbobr0t** [comment] 2023-10-25 15:46
nah bro you cant be fr, looks like you directly run the builder.py inside of the ui dir

**Comment by Kirbiv** [comment] 2023-10-25 15:47
when I open builder.bat it says when it end to download the modules: installed modules...
and then it doesn't do nothing bro

**Comment by Kirbiv** [comment] 2023-10-25 15:47
how the fk this work

**Comment by gumbobr0t** [comment] 2023-10-25 15:48
for the fifth fricking time, I NEED THE LOG FILES or an FULL AND EXACT ERROR

**Comment by gumbobr0t** [comment] 2023-10-25 15:48
i cant magically figure out what the issue is, rose is a highly complex program

**Comment by gumbobr0t** [comment] 2023-10-25 15:49
and yeah, the builder.bat installs modules into the venv and because there are many modules it can take a few minutes depending on how shit your connection is

**Comment by Kirbiv** [comment] 2023-10-25 15:49
builder.bat installed all files man

**Comment by gumbobr0t** [comment] 2023-10-25 15:49
open the builder.bat and just wait, if nothing happens after five minutes of total waiting, drag and drop the log files here

**Comment by gumbobr0t** [comment] 2023-10-25 15:50
its not fucking made to install files its not like a one-time launch setup, you run it and wait until the builder opens up

**Comment by gumbobr0t** [comment] 2023-10-25 15:50
> ![25 10 2023_17 49 52_REC](https://github.com/DamagingRose/Rose-Grabber/assets/111511458/7dc14f27-bd87-41d4-b33e-9ce24eb06d82)
> 
> this is what I see rn

yeah this can take some time as i said

**Comment by gumbobr0t** [comment] 2023-10-25 15:51
just wait bro be patient

**Comment by gumbobr0t** [comment] 2023-10-26 19:21
worked?

**Comment by something-0001** [comment] 2023-10-26 23:45
> worked?

No offense, but please be formal with communicating with issues, it only serves to make you appear worse as the owner of this project, which we both can agree isn't the best.

Anyways, replicate the behavior shown here; @Kirbiv || If it was closing beforehand, it should now show the error.

Make sure you have uninstalled all python installations but 3.11.5. (3.11.4 if you are fine with it.).

If there are further issues, let me know through here.
![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/36ac83c7-e216-4226-a062-e7785498350e)
![image](https://github.com/DamagingRose/Rose-Grabber/assets/14898342/61686903-7d74-448d-8c37-3c7ea6994386)

**Closed** 2023-10-29 20:26 UTC
Labels: help wanted
