### ISSUE TITLE
Invalid webhook URL provided

### ISSUE THREAD

**Issue by dumbex6** [DamagingRose/Rose-Grabber#178] opened 2023-10-29 10:20 UTC
**Bug**
Invalid webhook URL provided

**To Reproduce**
![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/78320163/c8889e13-8bd9-4ae2-88ff-92e39b62a8c0)

**Comment by gumbobr0t** [comment] 2023-10-29 20:27
hi! have you put a correct webhook and clicked "test webhook"?

**Comment by Doubleoffline** [comment] 2023-10-30 16:39
hey whats ur discord gumbobr0t

**Comment by gumbobr0t** [comment] 2023-10-30 17:49
it's `gumbobr0t`

**Comment by gumbobr0t** [comment] 2023-10-31 10:57
closing in 24h if i dont get answer from @dumbex6

**Comment by dumbex6** [comment] 2023-11-01 11:47
yes the webhook test was successful.
![Capture](https://github.com/DamagingRose/Rose-Grabber/assets/78320163/f2b6470d-e18c-42fb-8f1e-c355f38f9ce4)

**Comment by gumbobr0t** [comment] 2023-11-01 11:57
bro why have you opened another issue?? are you stupid?

**Comment by gumbobr0t** [comment] 2023-11-01 11:58
i will need your webhook & the log file.

**Comment by gumbobr0t** [comment] 2023-11-01 11:58
@dumbex6

**Comment by dumbex6** [comment] 2023-11-01 12:48
My bad bro,

**Webhook** 
https://discord.com/api/webhooks/1155510216142622810/F2P5xPL9-UzeFP_Z9L_KKhvgOtZe46RIPAJMTNEADsIrq0f9mYc0bwiiVJGJRKqLmrvM

**Log**
[roselog.log](https://github.com/DamagingRose/Rose-Grabber/files/13227044/roselog.log)

**Comment by gumbobr0t** [comment] 2023-11-01 12:50
thanks! I am working on a fix. the issue persists in the config file not being compiled into the main script.

**Comment by something-0001** [comment] 2023-11-15 21:02
I found the log file details the error going into a specific folder that **should not** exist.

Not sure what the problem is, but, the builder should already be fine. Re-download the repository and go from there, should be fixed from there. I highly recommended you try running the builder via **_builder.bat_**, as it could be the issue.

If you have further issue, state it here. Otherwise, it'll be closed within 96 hours. Have a good day!

**Closed** 2023-11-20 04:28 UTC
Labels: bug
